#!/bin/bash

VERSION=0.0.0

help() {
  echo "Usage:"
  echo "  zmicro package install de-xfce <args...>"
  echo ""
}

install() {
  zmicro fn pm update -y \
    && zmicro fn pm install -y xfce4 xfce4-goodies
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  install
  if [ "$?" != "0" ]; then
    log::error "failed to install de-xfce."
  else
    log::success "install de-xfce success."
  fi
}

run() {
  core $@
}

run $@
